// ============================================================
// Africa SDG Scorecard — REAL DATA
// Auto-generated by fetch_sdg_data.py
// Sources: World Bank API, WHO, FAO (all CC BY / open license)
// Generated: 2026-04-25
// ============================================================

export const SDG_GOALS = [
  { id: 1,  label: 'No Poverty',          color: '#e5243b', icon: '🏠' },
  { id: 2,  label: 'Zero Hunger',         color: '#dda63a', icon: '🌾' },
  { id: 3,  label: 'Good Health',         color: '#4c9f38', icon: '🏥' },
  { id: 4,  label: 'Quality Education',   color: '#c5192d', icon: '📚' },
  { id: 7,  label: 'Clean Energy',        color: '#fcc30b', icon: '⚡' },
  { id: 8,  label: 'Decent Work',         color: '#a21942', icon: '💼' },
  { id: 13, label: 'Climate Action',      color: '#3f7e44', icon: '🌍' },
]

export const REGIONS = [
  'East Africa', 'West Africa', 'Southern Africa', 'North Africa', 'Central Africa',
]

export const countries = [
  {
    "iso": "CPV",
    "name": "Cabo Verde",
    "flag": "🇨🇻",
    "region": "West Africa",
    "population": 0.5,
    "incomeGroup": "Upper-middle",
    "sdgScore": 95.2,
    "sdgRank": 1,
    "goals": {
      2: {
        "score": 80.9,
        "status": "green",
        "keyIndicator": "Undernourishment rate",
        "value": 13.5,
        "unit": "%",
        "trend": "stable",
        "source": "FAO / World Bank 2023"
      },
      3: {
        "score": 100,
        "status": "green",
        "keyIndicator": "Under-5 mortality rate",
        "value": 11.1,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      4: {
        "score": 98.7,
        "status": "green",
        "keyIndicator": "Primary completion rate",
        "value": 99.1,
        "unit": "%",
        "trend": "stable",
        "source": "UNESCO / World Bank 2022"
      },
      7: {
        "score": 98.6,
        "status": "green",
        "keyIndicator": "Access to electricity",
        "value": 98.6,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 97.7,
        "status": "green",
        "keyIndicator": "GDP per capita growth",
        "value": 6.72,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "DZA",
    "name": "Algeria",
    "flag": "🇩🇿",
    "region": "North Africa",
    "population": 46.8,
    "incomeGroup": "Upper-middle",
    "sdgScore": 91.6,
    "sdgRank": 2,
    "goals": {
      2: {
        "score": 100,
        "status": "green",
        "keyIndicator": "Undernourishment rate",
        "value": 2.5,
        "unit": "%",
        "trend": "stable",
        "source": "FAO / World Bank 2023"
      },
      3: {
        "score": 100,
        "status": "green",
        "keyIndicator": "Under-5 mortality rate",
        "value": 21.6,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      4: {
        "score": 97.5,
        "status": "green",
        "keyIndicator": "Primary completion rate",
        "value": 98.24,
        "unit": "%",
        "trend": "stable",
        "source": "UNESCO / World Bank 2025"
      },
      7: {
        "score": 100,
        "status": "green",
        "keyIndicator": "Access to electricity",
        "value": 100.0,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 60.5,
        "status": "yellow",
        "keyIndicator": "GDP per capita growth",
        "value": 2.26,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "MAR",
    "name": "Morocco",
    "flag": "🇲🇦",
    "region": "North Africa",
    "population": 38.1,
    "incomeGroup": "Lower-middle",
    "sdgScore": 91.4,
    "sdgRank": 3,
    "goals": {
      2: {
        "score": 92.2,
        "status": "green",
        "keyIndicator": "Undernourishment rate",
        "value": 7.0,
        "unit": "%",
        "trend": "stable",
        "source": "FAO / World Bank 2023"
      },
      3: {
        "score": 100,
        "status": "green",
        "keyIndicator": "Under-5 mortality rate",
        "value": 15.7,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      4: {
        "score": 100,
        "status": "green",
        "keyIndicator": "Primary completion rate",
        "value": 106.37,
        "unit": "%",
        "trend": "stable",
        "source": "UNESCO / World Bank 2024"
      },
      7: {
        "score": 100,
        "status": "green",
        "keyIndicator": "Access to electricity",
        "value": 100.0,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 64.8,
        "status": "yellow",
        "keyIndicator": "GDP per capita growth",
        "value": 2.77,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "MUS",
    "name": "Mauritius",
    "flag": "🇲🇺",
    "region": "East Africa",
    "population": 1.2,
    "incomeGroup": "Upper-middle",
    "sdgScore": 90.0,
    "sdgRank": 4,
    "goals": {
      2: {
        "score": 89.2,
        "status": "green",
        "keyIndicator": "Undernourishment rate",
        "value": 8.7,
        "unit": "%",
        "trend": "stable",
        "source": "FAO / World Bank 2023"
      },
      3: {
        "score": 100,
        "status": "green",
        "keyIndicator": "Under-5 mortality rate",
        "value": 15.4,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      4: {
        "score": 76.1,
        "status": "green",
        "keyIndicator": "Primary completion rate",
        "value": 83.25,
        "unit": "%",
        "trend": "stable",
        "source": "UNESCO / World Bank 2024"
      },
      7: {
        "score": 100,
        "status": "green",
        "keyIndicator": "Access to electricity",
        "value": 100.0,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 84.8,
        "status": "green",
        "keyIndicator": "GDP per capita growth",
        "value": 5.17,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "TUN",
    "name": "Tunisia",
    "flag": "🇹🇳",
    "region": "North Africa",
    "population": 12.3,
    "incomeGroup": "Lower-middle",
    "sdgScore": 89.8,
    "sdgRank": 5,
    "goals": {
      1: {
        "score": 99.1,
        "status": "green",
        "keyIndicator": "Poverty headcount (<$2.15/day)",
        "value": 0.7,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2021"
      },
      2: {
        "score": 99.1,
        "status": "green",
        "keyIndicator": "Undernourishment rate",
        "value": 3.0,
        "unit": "%",
        "trend": "stable",
        "source": "FAO / World Bank 2023"
      },
      3: {
        "score": 100,
        "status": "green",
        "keyIndicator": "Under-5 mortality rate",
        "value": 12.1,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      4: {
        "score": 90.9,
        "status": "green",
        "keyIndicator": "Primary completion rate",
        "value": 93.63,
        "unit": "%",
        "trend": "stable",
        "source": "UNESCO / World Bank 2021"
      },
      7: {
        "score": 100,
        "status": "green",
        "keyIndicator": "Access to electricity",
        "value": 100.0,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 49.8,
        "status": "orange",
        "keyIndicator": "GDP per capita growth",
        "value": 0.98,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "GHA",
    "name": "Ghana",
    "flag": "🇬🇭",
    "region": "West Africa",
    "population": 34.4,
    "incomeGroup": "Lower-middle",
    "sdgScore": 89.0,
    "sdgRank": 6,
    "goals": {
      2: {
        "score": 93.4,
        "status": "green",
        "keyIndicator": "Undernourishment rate",
        "value": 6.3,
        "unit": "%",
        "trend": "stable",
        "source": "FAO / World Bank 2023"
      },
      3: {
        "score": 93.8,
        "status": "green",
        "keyIndicator": "Under-5 mortality rate",
        "value": 35.9,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      4: {
        "score": 96.4,
        "status": "green",
        "keyIndicator": "Primary completion rate",
        "value": 97.5,
        "unit": "%",
        "trend": "stable",
        "source": "UNESCO / World Bank 2024"
      },
      7: {
        "score": 89.5,
        "status": "green",
        "keyIndicator": "Access to electricity",
        "value": 89.5,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 71.9,
        "status": "green",
        "keyIndicator": "GDP per capita growth",
        "value": 3.63,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "EGY",
    "name": "Egypt",
    "flag": "🇪🇬",
    "region": "North Africa",
    "population": 116.5,
    "incomeGroup": "Lower-middle",
    "sdgScore": 88.4,
    "sdgRank": 7,
    "goals": {
      1: {
        "score": 98.2,
        "status": "green",
        "keyIndicator": "Poverty headcount (<$2.15/day)",
        "value": 1.4,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2021"
      },
      2: {
        "score": 88.0,
        "status": "green",
        "keyIndicator": "Undernourishment rate",
        "value": 9.4,
        "unit": "%",
        "trend": "stable",
        "source": "FAO / World Bank 2023"
      },
      3: {
        "score": 100,
        "status": "green",
        "keyIndicator": "Under-5 mortality rate",
        "value": 22.4,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      4: {
        "score": 97.4,
        "status": "green",
        "keyIndicator": "Primary completion rate",
        "value": 98.21,
        "unit": "%",
        "trend": "stable",
        "source": "UNESCO / World Bank 2024"
      },
      7: {
        "score": 100,
        "status": "green",
        "keyIndicator": "Access to electricity",
        "value": 100.0,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 47.0,
        "status": "orange",
        "keyIndicator": "GDP per capita growth",
        "value": 0.64,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "SWZ",
    "name": "Eswatini",
    "flag": "🇸🇿",
    "region": "Southern Africa",
    "population": 1.2,
    "incomeGroup": "Lower-middle",
    "sdgScore": 80.5,
    "sdgRank": 8,
    "goals": {
      2: {
        "score": 78.8,
        "status": "green",
        "keyIndicator": "Undernourishment rate",
        "value": 14.7,
        "unit": "%",
        "trend": "stable",
        "source": "FAO / World Bank 2023"
      },
      3: {
        "score": 88.5,
        "status": "green",
        "keyIndicator": "Under-5 mortality rate",
        "value": 45.1,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      4: {
        "score": 90.9,
        "status": "green",
        "keyIndicator": "Primary completion rate",
        "value": 93.61,
        "unit": "%",
        "trend": "stable",
        "source": "UNESCO / World Bank 2023"
      },
      7: {
        "score": 86.4,
        "status": "green",
        "keyIndicator": "Access to electricity",
        "value": 86.4,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 57.9,
        "status": "yellow",
        "keyIndicator": "GDP per capita growth",
        "value": 1.95,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "DJI",
    "name": "Djibouti",
    "flag": "🇩🇯",
    "region": "East Africa",
    "population": 1.2,
    "incomeGroup": "Lower-middle",
    "sdgScore": 80.3,
    "sdgRank": 9,
    "goals": {
      2: {
        "score": 81.9,
        "status": "green",
        "keyIndicator": "Undernourishment rate",
        "value": 12.9,
        "unit": "%",
        "trend": "stable",
        "source": "FAO / World Bank 2023"
      },
      3: {
        "score": 86.3,
        "status": "green",
        "keyIndicator": "Under-5 mortality rate",
        "value": 48.9,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      7: {
        "score": 65.2,
        "status": "yellow",
        "keyIndicator": "Access to electricity",
        "value": 65.2,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 87.8,
        "status": "green",
        "keyIndicator": "GDP per capita growth",
        "value": 5.54,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "ZAF",
    "name": "South Africa",
    "flag": "🇿🇦",
    "region": "Southern Africa",
    "population": 64.0,
    "incomeGroup": "Upper-middle",
    "sdgScore": 79.4,
    "sdgRank": 10,
    "goals": {
      1: {
        "score": 78.2,
        "status": "green",
        "keyIndicator": "Poverty headcount (<$2.15/day)",
        "value": 17.4,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2022"
      },
      2: {
        "score": 87.0,
        "status": "green",
        "keyIndicator": "Undernourishment rate",
        "value": 10.0,
        "unit": "%",
        "trend": "stable",
        "source": "FAO / World Bank 2023"
      },
      3: {
        "score": 94.2,
        "status": "green",
        "keyIndicator": "Under-5 mortality rate",
        "value": 35.1,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      4: {
        "score": 93.3,
        "status": "green",
        "keyIndicator": "Primary completion rate",
        "value": 95.33,
        "unit": "%",
        "trend": "stable",
        "source": "UNESCO / World Bank 2023"
      },
      7: {
        "score": 87.7,
        "status": "green",
        "keyIndicator": "Access to electricity",
        "value": 87.7,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 35.8,
        "status": "red",
        "keyIndicator": "GDP per capita growth",
        "value": -0.71,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "COM",
    "name": "Comoros",
    "flag": "🇰🇲",
    "region": "East Africa",
    "population": 0.9,
    "incomeGroup": "Lower-middle",
    "sdgScore": 77.9,
    "sdgRank": 11,
    "goals": {
      1: {
        "score": 93.6,
        "status": "green",
        "keyIndicator": "Poverty headcount (<$2.15/day)",
        "value": 5.1,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      },
      2: {
        "score": 77.6,
        "status": "green",
        "keyIndicator": "Undernourishment rate",
        "value": 15.4,
        "unit": "%",
        "trend": "stable",
        "source": "FAO / World Bank 2023"
      },
      3: {
        "score": 92.0,
        "status": "green",
        "keyIndicator": "Under-5 mortality rate",
        "value": 39.0,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      4: {
        "score": 61.0,
        "status": "yellow",
        "keyIndicator": "Primary completion rate",
        "value": 72.72,
        "unit": "%",
        "trend": "stable",
        "source": "UNESCO / World Bank 2024"
      },
      7: {
        "score": 89.8,
        "status": "green",
        "keyIndicator": "Access to electricity",
        "value": 89.8,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 53.3,
        "status": "orange",
        "keyIndicator": "GDP per capita growth",
        "value": 1.4,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "SEN",
    "name": "Senegal",
    "flag": "🇸🇳",
    "region": "West Africa",
    "population": 18.5,
    "incomeGroup": "Lower-middle",
    "sdgScore": 76.6,
    "sdgRank": 12,
    "goals": {
      1: {
        "score": 77.6,
        "status": "green",
        "keyIndicator": "Poverty headcount (<$2.15/day)",
        "value": 17.9,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2021"
      },
      2: {
        "score": 95.5,
        "status": "green",
        "keyIndicator": "Undernourishment rate",
        "value": 5.1,
        "unit": "%",
        "trend": "stable",
        "source": "FAO / World Bank 2023"
      },
      3: {
        "score": 93.4,
        "status": "green",
        "keyIndicator": "Under-5 mortality rate",
        "value": 36.5,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      4: {
        "score": 46.9,
        "status": "orange",
        "keyIndicator": "Primary completion rate",
        "value": 62.86,
        "unit": "%",
        "trend": "stable",
        "source": "UNESCO / World Bank 2024"
      },
      7: {
        "score": 74.2,
        "status": "green",
        "keyIndicator": "Access to electricity",
        "value": 74.2,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 71.9,
        "status": "green",
        "keyIndicator": "GDP per capita growth",
        "value": 3.63,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "GAB",
    "name": "Gabon",
    "flag": "🇬🇦",
    "region": "Central Africa",
    "population": 2.5,
    "incomeGroup": "Upper-middle",
    "sdgScore": 75.4,
    "sdgRank": 13,
    "goals": {
      2: {
        "score": 60.3,
        "status": "yellow",
        "keyIndicator": "Undernourishment rate",
        "value": 25.3,
        "unit": "%",
        "trend": "stable",
        "source": "FAO / World Bank 2023"
      },
      3: {
        "score": 95.7,
        "status": "green",
        "keyIndicator": "Under-5 mortality rate",
        "value": 32.6,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      7: {
        "score": 94.1,
        "status": "green",
        "keyIndicator": "Access to electricity",
        "value": 94.1,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 51.6,
        "status": "orange",
        "keyIndicator": "GDP per capita growth",
        "value": 1.19,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "MRT",
    "name": "Mauritania",
    "flag": "🇲🇷",
    "region": "West Africa",
    "population": 5.2,
    "incomeGroup": "Lower-middle",
    "sdgScore": 75.4,
    "sdgRank": 14,
    "goals": {
      2: {
        "score": 89.2,
        "status": "green",
        "keyIndicator": "Undernourishment rate",
        "value": 8.7,
        "unit": "%",
        "trend": "stable",
        "source": "FAO / World Bank 2023"
      },
      3: {
        "score": 93.2,
        "status": "green",
        "keyIndicator": "Under-5 mortality rate",
        "value": 36.9,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      7: {
        "score": 50.3,
        "status": "orange",
        "keyIndicator": "Access to electricity",
        "value": 50.3,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 69.1,
        "status": "yellow",
        "keyIndicator": "GDP per capita growth",
        "value": 3.29,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "CIV",
    "name": "Côte d'Ivoire",
    "flag": "🇨🇮",
    "region": "West Africa",
    "population": 31.9,
    "incomeGroup": "Lower-middle",
    "sdgScore": 75.2,
    "sdgRank": 15,
    "goals": {
      1: {
        "score": 74.0,
        "status": "green",
        "keyIndicator": "Poverty headcount (<$2.15/day)",
        "value": 20.8,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2021"
      },
      2: {
        "score": 85.0,
        "status": "green",
        "keyIndicator": "Undernourishment rate",
        "value": 11.1,
        "unit": "%",
        "trend": "stable",
        "source": "FAO / World Bank 2023"
      },
      3: {
        "score": 77.4,
        "status": "green",
        "keyIndicator": "Under-5 mortality rate",
        "value": 64.5,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      4: {
        "score": 71.8,
        "status": "green",
        "keyIndicator": "Primary completion rate",
        "value": 80.24,
        "unit": "%",
        "trend": "stable",
        "source": "UNESCO / World Bank 2024"
      },
      7: {
        "score": 72.4,
        "status": "green",
        "keyIndicator": "Access to electricity",
        "value": 72.4,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 70.6,
        "status": "green",
        "keyIndicator": "GDP per capita growth",
        "value": 3.47,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "TGO",
    "name": "Togo",
    "flag": "🇹🇬",
    "region": "West Africa",
    "population": 9.5,
    "incomeGroup": "Low",
    "sdgScore": 75.1,
    "sdgRank": 16,
    "goals": {
      1: {
        "score": 56.6,
        "status": "yellow",
        "keyIndicator": "Poverty headcount (<$2.15/day)",
        "value": 34.7,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2021"
      },
      2: {
        "score": 88.5,
        "status": "green",
        "keyIndicator": "Undernourishment rate",
        "value": 9.1,
        "unit": "%",
        "trend": "stable",
        "source": "FAO / World Bank 2023"
      },
      3: {
        "score": 82.2,
        "status": "green",
        "keyIndicator": "Under-5 mortality rate",
        "value": 56.1,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      4: {
        "score": 87.5,
        "status": "green",
        "keyIndicator": "Primary completion rate",
        "value": 91.22,
        "unit": "%",
        "trend": "stable",
        "source": "UNESCO / World Bank 2024"
      },
      7: {
        "score": 59.2,
        "status": "yellow",
        "keyIndicator": "Access to electricity",
        "value": 59.2,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 76.4,
        "status": "green",
        "keyIndicator": "GDP per capita growth",
        "value": 4.17,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "GMB",
    "name": "Gambia",
    "flag": "🇬🇲",
    "region": "West Africa",
    "population": 2.8,
    "incomeGroup": "Low",
    "sdgScore": 75.0,
    "sdgRank": 17,
    "goals": {
      1: {
        "score": 72.5,
        "status": "green",
        "keyIndicator": "Poverty headcount (<$2.15/day)",
        "value": 22.0,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2020"
      },
      2: {
        "score": 75.1,
        "status": "green",
        "keyIndicator": "Undernourishment rate",
        "value": 16.8,
        "unit": "%",
        "trend": "stable",
        "source": "FAO / World Bank 2023"
      },
      3: {
        "score": 90.1,
        "status": "green",
        "keyIndicator": "Under-5 mortality rate",
        "value": 42.4,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      4: {
        "score": 77.4,
        "status": "green",
        "keyIndicator": "Primary completion rate",
        "value": 84.17,
        "unit": "%",
        "trend": "stable",
        "source": "UNESCO / World Bank 2025"
      },
      7: {
        "score": 66.9,
        "status": "yellow",
        "keyIndicator": "Access to electricity",
        "value": 66.9,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 68.1,
        "status": "yellow",
        "keyIndicator": "GDP per capita growth",
        "value": 3.17,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "LBY",
    "name": "Libya",
    "flag": "🇱🇾",
    "region": "North Africa",
    "population": 7.4,
    "incomeGroup": "Upper-middle",
    "sdgScore": 74.4,
    "sdgRank": 18,
    "goals": {
      2: {
        "score": 75.7,
        "status": "green",
        "keyIndicator": "Undernourishment rate",
        "value": 16.5,
        "unit": "%",
        "trend": "stable",
        "source": "FAO / World Bank 2023"
      },
      3: {
        "score": 100,
        "status": "green",
        "keyIndicator": "Under-5 mortality rate",
        "value": 9.8,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      7: {
        "score": 73.2,
        "status": "green",
        "keyIndicator": "Access to electricity",
        "value": 73.2,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 48.8,
        "status": "orange",
        "keyIndicator": "GDP per capita growth",
        "value": 0.86,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "STP",
    "name": "São Tomé and Príncipe",
    "flag": "🇸🇹",
    "region": "Central Africa",
    "population": 0.2,
    "incomeGroup": "Lower-middle",
    "sdgScore": 72.4,
    "sdgRank": 19,
    "goals": {
      2: {
        "score": 74.1,
        "status": "green",
        "keyIndicator": "Undernourishment rate",
        "value": 17.4,
        "unit": "%",
        "trend": "stable",
        "source": "FAO / World Bank 2023"
      },
      3: {
        "score": 100,
        "status": "green",
        "keyIndicator": "Under-5 mortality rate",
        "value": 13.6,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      7: {
        "score": 81.3,
        "status": "green",
        "keyIndicator": "Access to electricity",
        "value": 81.3,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 34.2,
        "status": "red",
        "keyIndicator": "GDP per capita growth",
        "value": -0.9,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "NAM",
    "name": "Namibia",
    "flag": "🇳🇦",
    "region": "Southern Africa",
    "population": 3.0,
    "incomeGroup": "Lower-middle",
    "sdgScore": 71.7,
    "sdgRank": 20,
    "goals": {
      2: {
        "score": 72.9,
        "status": "green",
        "keyIndicator": "Undernourishment rate",
        "value": 18.1,
        "unit": "%",
        "trend": "stable",
        "source": "FAO / World Bank 2023"
      },
      3: {
        "score": 91.7,
        "status": "green",
        "keyIndicator": "Under-5 mortality rate",
        "value": 39.5,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      4: {
        "score": 83.7,
        "status": "green",
        "keyIndicator": "Primary completion rate",
        "value": 88.56,
        "unit": "%",
        "trend": "stable",
        "source": "UNESCO / World Bank 2024"
      },
      7: {
        "score": 56.7,
        "status": "yellow",
        "keyIndicator": "Access to electricity",
        "value": 56.7,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 53.5,
        "status": "orange",
        "keyIndicator": "GDP per capita growth",
        "value": 1.42,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "CMR",
    "name": "Cameroon",
    "flag": "🇨🇲",
    "region": "Central Africa",
    "population": 29.1,
    "incomeGroup": "Lower-middle",
    "sdgScore": 70.9,
    "sdgRank": 21,
    "goals": {
      1: {
        "score": 66.6,
        "status": "yellow",
        "keyIndicator": "Poverty headcount (<$2.15/day)",
        "value": 26.7,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2021"
      },
      2: {
        "score": 96.0,
        "status": "green",
        "keyIndicator": "Undernourishment rate",
        "value": 4.8,
        "unit": "%",
        "trend": "stable",
        "source": "FAO / World Bank 2023"
      },
      3: {
        "score": 77.3,
        "status": "green",
        "keyIndicator": "Under-5 mortality rate",
        "value": 64.8,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      4: {
        "score": 64.7,
        "status": "yellow",
        "keyIndicator": "Primary completion rate",
        "value": 75.29,
        "unit": "%",
        "trend": "stable",
        "source": "UNESCO / World Bank 2024"
      },
      7: {
        "score": 72.0,
        "status": "green",
        "keyIndicator": "Access to electricity",
        "value": 72.0,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 48.8,
        "status": "orange",
        "keyIndicator": "GDP per capita growth",
        "value": 0.85,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "RWA",
    "name": "Rwanda",
    "flag": "🇷🇼",
    "region": "East Africa",
    "population": 14.3,
    "incomeGroup": "Low",
    "sdgScore": 69.9,
    "sdgRank": 22,
    "goals": {
      1: {
        "score": 51.8,
        "status": "orange",
        "keyIndicator": "Poverty headcount (<$2.15/day)",
        "value": 38.6,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      2: {
        "score": 61.9,
        "status": "yellow",
        "keyIndicator": "Undernourishment rate",
        "value": 24.4,
        "unit": "%",
        "trend": "stable",
        "source": "FAO / World Bank 2023"
      },
      3: {
        "score": 92.7,
        "status": "green",
        "keyIndicator": "Under-5 mortality rate",
        "value": 37.7,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      4: {
        "score": 52.6,
        "status": "orange",
        "keyIndicator": "Primary completion rate",
        "value": 66.82,
        "unit": "%",
        "trend": "stable",
        "source": "UNESCO / World Bank 2024"
      },
      7: {
        "score": 63.9,
        "status": "yellow",
        "keyIndicator": "Access to electricity",
        "value": 63.9,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 96.5,
        "status": "green",
        "keyIndicator": "GDP per capita growth",
        "value": 6.58,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "TZA",
    "name": "Tanzania",
    "flag": "🇹🇿",
    "region": "East Africa",
    "population": 68.6,
    "incomeGroup": "Lower-middle",
    "sdgScore": 68.2,
    "sdgRank": 23,
    "goals": {
      2: {
        "score": 69.2,
        "status": "yellow",
        "keyIndicator": "Undernourishment rate",
        "value": 20.2,
        "unit": "%",
        "trend": "stable",
        "source": "FAO / World Bank 2023"
      },
      3: {
        "score": 93.1,
        "status": "green",
        "keyIndicator": "Under-5 mortality rate",
        "value": 37.0,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      4: {
        "score": 67.6,
        "status": "yellow",
        "keyIndicator": "Primary completion rate",
        "value": 77.33,
        "unit": "%",
        "trend": "stable",
        "source": "UNESCO / World Bank 2024"
      },
      7: {
        "score": 48.3,
        "status": "orange",
        "keyIndicator": "Access to electricity",
        "value": 48.3,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 62.9,
        "status": "yellow",
        "keyIndicator": "GDP per capita growth",
        "value": 2.55,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "UGA",
    "name": "Uganda",
    "flag": "🇺🇬",
    "region": "East Africa",
    "population": 50.0,
    "incomeGroup": "Low",
    "sdgScore": 68.0,
    "sdgRank": 24,
    "goals": {
      2: {
        "score": 66.1,
        "status": "yellow",
        "keyIndicator": "Undernourishment rate",
        "value": 22.0,
        "unit": "%",
        "trend": "stable",
        "source": "FAO / World Bank 2023"
      },
      3: {
        "score": 86.5,
        "status": "green",
        "keyIndicator": "Under-5 mortality rate",
        "value": 48.7,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      7: {
        "score": 51.5,
        "status": "orange",
        "keyIndicator": "Access to electricity",
        "value": 51.5,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 68.1,
        "status": "yellow",
        "keyIndicator": "GDP per capita growth",
        "value": 3.17,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "BWA",
    "name": "Botswana",
    "flag": "🇧🇼",
    "region": "Southern Africa",
    "population": 2.5,
    "incomeGroup": "Upper-middle",
    "sdgScore": 67.5,
    "sdgRank": 25,
    "goals": {
      2: {
        "score": 62.6,
        "status": "yellow",
        "keyIndicator": "Undernourishment rate",
        "value": 24.0,
        "unit": "%",
        "trend": "stable",
        "source": "FAO / World Bank 2023"
      },
      3: {
        "score": 95.3,
        "status": "green",
        "keyIndicator": "Under-5 mortality rate",
        "value": 33.3,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      4: {
        "score": 100,
        "status": "green",
        "keyIndicator": "Primary completion rate",
        "value": 101.53,
        "unit": "%",
        "trend": "stable",
        "source": "UNESCO / World Bank 2022"
      },
      7: {
        "score": 76.0,
        "status": "green",
        "keyIndicator": "Access to electricity",
        "value": 76.0,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 3.7,
        "status": "red",
        "keyIndicator": "GDP per capita growth",
        "value": -4.56,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "BEN",
    "name": "Benin",
    "flag": "🇧🇯",
    "region": "West Africa",
    "population": 14.5,
    "incomeGroup": "Lower-middle",
    "sdgScore": 66.9,
    "sdgRank": 26,
    "goals": {
      1: {
        "score": 66.0,
        "status": "yellow",
        "keyIndicator": "Poverty headcount (<$2.15/day)",
        "value": 27.2,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2021"
      },
      2: {
        "score": 79.5,
        "status": "green",
        "keyIndicator": "Undernourishment rate",
        "value": 14.3,
        "unit": "%",
        "trend": "stable",
        "source": "FAO / World Bank 2023"
      },
      3: {
        "score": 71.6,
        "status": "green",
        "keyIndicator": "Under-5 mortality rate",
        "value": 74.7,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      4: {
        "score": 45.2,
        "status": "orange",
        "keyIndicator": "Primary completion rate",
        "value": 61.64,
        "unit": "%",
        "trend": "stable",
        "source": "UNESCO / World Bank 2022"
      },
      7: {
        "score": 57.0,
        "status": "yellow",
        "keyIndicator": "Access to electricity",
        "value": 57.0,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 82.0,
        "status": "green",
        "keyIndicator": "GDP per capita growth",
        "value": 4.84,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "ZWE",
    "name": "Zimbabwe",
    "flag": "🇿🇼",
    "region": "Southern Africa",
    "population": 16.6,
    "incomeGroup": "Lower-middle",
    "sdgScore": 66.1,
    "sdgRank": 27,
    "goals": {
      2: {
        "score": 70.1,
        "status": "green",
        "keyIndicator": "Undernourishment rate",
        "value": 19.7,
        "unit": "%",
        "trend": "stable",
        "source": "FAO / World Bank 2023"
      },
      3: {
        "score": 77.3,
        "status": "green",
        "keyIndicator": "Under-5 mortality rate",
        "value": 64.7,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      4: {
        "score": 79.9,
        "status": "green",
        "keyIndicator": "Primary completion rate",
        "value": 85.96,
        "unit": "%",
        "trend": "stable",
        "source": "UNESCO / World Bank 2024"
      },
      7: {
        "score": 62.0,
        "status": "yellow",
        "keyIndicator": "Access to electricity",
        "value": 62.0,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 41.2,
        "status": "orange",
        "keyIndicator": "GDP per capita growth",
        "value": -0.05,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "GIN",
    "name": "Guinea",
    "flag": "🇬🇳",
    "region": "West Africa",
    "population": 14.8,
    "incomeGroup": "Lower-middle",
    "sdgScore": 65.7,
    "sdgRank": 28,
    "goals": {
      2: {
        "score": 84.5,
        "status": "green",
        "keyIndicator": "Undernourishment rate",
        "value": 11.4,
        "unit": "%",
        "trend": "stable",
        "source": "FAO / World Bank 2023"
      },
      3: {
        "score": 61.7,
        "status": "yellow",
        "keyIndicator": "Under-5 mortality rate",
        "value": 92.1,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      7: {
        "score": 51.1,
        "status": "orange",
        "keyIndicator": "Access to electricity",
        "value": 51.1,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 65.5,
        "status": "yellow",
        "keyIndicator": "GDP per capita growth",
        "value": 2.86,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "GNQ",
    "name": "Equatorial Guinea",
    "flag": "🇬🇶",
    "region": "Central Africa",
    "population": 1.9,
    "incomeGroup": "Upper-middle",
    "sdgScore": 65.1,
    "sdgRank": 29,
    "goals": {
      1: {
        "score": 89.0,
        "status": "green",
        "keyIndicator": "Poverty headcount (<$2.15/day)",
        "value": 8.8,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2022"
      },
      3: {
        "score": 75.4,
        "status": "green",
        "keyIndicator": "Under-5 mortality rate",
        "value": 68.0,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      7: {
        "score": 66.9,
        "status": "yellow",
        "keyIndicator": "Access to electricity",
        "value": 66.9,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 29.2,
        "status": "red",
        "keyIndicator": "GDP per capita growth",
        "value": -1.49,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "ERI",
    "name": "Eritrea",
    "flag": "🇪🇷",
    "region": "East Africa",
    "population": 3.5,
    "incomeGroup": "Unknown",
    "sdgScore": 64.6,
    "sdgRank": 30,
    "goals": {
      3: {
        "score": 94.7,
        "status": "green",
        "keyIndicator": "Under-5 mortality rate",
        "value": 34.3,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      4: {
        "score": 44.7,
        "status": "orange",
        "keyIndicator": "Primary completion rate",
        "value": 61.28,
        "unit": "%",
        "trend": "stable",
        "source": "UNESCO / World Bank 2022"
      },
      7: {
        "score": 54.4,
        "status": "orange",
        "keyIndicator": "Access to electricity",
        "value": 54.4,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      }
    }
  },
  {
    "iso": "ETH",
    "name": "Ethiopia",
    "flag": "🇪🇹",
    "region": "East Africa",
    "population": 132.1,
    "incomeGroup": "Low",
    "sdgScore": 63.9,
    "sdgRank": 31,
    "goals": {
      1: {
        "score": 51.8,
        "status": "orange",
        "keyIndicator": "Poverty headcount (<$2.15/day)",
        "value": 38.6,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2021"
      },
      2: {
        "score": 70.1,
        "status": "green",
        "keyIndicator": "Undernourishment rate",
        "value": 19.7,
        "unit": "%",
        "trend": "stable",
        "source": "FAO / World Bank 2023"
      },
      3: {
        "score": 88.9,
        "status": "green",
        "keyIndicator": "Under-5 mortality rate",
        "value": 44.5,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      4: {
        "score": 34.9,
        "status": "red",
        "keyIndicator": "Primary completion rate",
        "value": 54.44,
        "unit": "%",
        "trend": "stable",
        "source": "UNESCO / World Bank 2024"
      },
      7: {
        "score": 55.4,
        "status": "yellow",
        "keyIndicator": "Access to electricity",
        "value": 55.4,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 82.3,
        "status": "green",
        "keyIndicator": "GDP per capita growth",
        "value": 4.87,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "SLE",
    "name": "Sierra Leone",
    "flag": "🇸🇱",
    "region": "West Africa",
    "population": 8.6,
    "incomeGroup": "Low",
    "sdgScore": 63.7,
    "sdgRank": 32,
    "goals": {
      2: {
        "score": 62.4,
        "status": "yellow",
        "keyIndicator": "Undernourishment rate",
        "value": 24.1,
        "unit": "%",
        "trend": "stable",
        "source": "FAO / World Bank 2023"
      },
      3: {
        "score": 62.6,
        "status": "yellow",
        "keyIndicator": "Under-5 mortality rate",
        "value": 90.5,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      4: {
        "score": 98.9,
        "status": "green",
        "keyIndicator": "Primary completion rate",
        "value": 99.2,
        "unit": "%",
        "trend": "stable",
        "source": "UNESCO / World Bank 2024"
      },
      7: {
        "score": 35.5,
        "status": "red",
        "keyIndicator": "Access to electricity",
        "value": 35.5,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 59.2,
        "status": "yellow",
        "keyIndicator": "GDP per capita growth",
        "value": 2.1,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "KEN",
    "name": "Kenya",
    "flag": "🇰🇪",
    "region": "East Africa",
    "population": 56.4,
    "incomeGroup": "Lower-middle",
    "sdgScore": 63.2,
    "sdgRank": 33,
    "goals": {
      1: {
        "score": 43.1,
        "status": "orange",
        "keyIndicator": "Poverty headcount (<$2.15/day)",
        "value": 45.5,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2022"
      },
      2: {
        "score": 40.3,
        "status": "orange",
        "keyIndicator": "Undernourishment rate",
        "value": 36.8,
        "unit": "%",
        "trend": "stable",
        "source": "FAO / World Bank 2023"
      },
      3: {
        "score": 92.1,
        "status": "green",
        "keyIndicator": "Under-5 mortality rate",
        "value": 38.8,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      7: {
        "score": 76.2,
        "status": "green",
        "keyIndicator": "Access to electricity",
        "value": 76.2,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 64.1,
        "status": "yellow",
        "keyIndicator": "GDP per capita growth",
        "value": 2.69,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "LSO",
    "name": "Lesotho",
    "flag": "🇱🇸",
    "region": "Southern Africa",
    "population": 2.3,
    "incomeGroup": "Lower-middle",
    "sdgScore": 61.5,
    "sdgRank": 34,
    "goals": {
      3: {
        "score": 80.0,
        "status": "green",
        "keyIndicator": "Under-5 mortality rate",
        "value": 60.0,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      4: {
        "score": 52.8,
        "status": "orange",
        "keyIndicator": "Primary completion rate",
        "value": 66.96,
        "unit": "%",
        "trend": "stable",
        "source": "UNESCO / World Bank 2023"
      },
      7: {
        "score": 57.3,
        "status": "yellow",
        "keyIndicator": "Access to electricity",
        "value": 57.3,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 55.9,
        "status": "yellow",
        "keyIndicator": "GDP per capita growth",
        "value": 1.71,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "COG",
    "name": "Republic of Congo",
    "flag": "🇨🇬",
    "region": "Central Africa",
    "population": 6.3,
    "incomeGroup": "Lower-middle",
    "sdgScore": 60.7,
    "sdgRank": 35,
    "goals": {
      2: {
        "score": 58.4,
        "status": "yellow",
        "keyIndicator": "Undernourishment rate",
        "value": 26.4,
        "unit": "%",
        "trend": "stable",
        "source": "FAO / World Bank 2023"
      },
      3: {
        "score": 91.9,
        "status": "green",
        "keyIndicator": "Under-5 mortality rate",
        "value": 39.1,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      4: {
        "score": 58.8,
        "status": "yellow",
        "keyIndicator": "Primary completion rate",
        "value": 71.14,
        "unit": "%",
        "trend": "stable",
        "source": "UNESCO / World Bank 2023"
      },
      7: {
        "score": 51.3,
        "status": "orange",
        "keyIndicator": "Access to electricity",
        "value": 51.3,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 42.9,
        "status": "orange",
        "keyIndicator": "GDP per capita growth",
        "value": 0.15,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "MLI",
    "name": "Mali",
    "flag": "🇲🇱",
    "region": "West Africa",
    "population": 24.5,
    "incomeGroup": "Low",
    "sdgScore": 58.2,
    "sdgRank": 36,
    "goals": {
      1: {
        "score": 54.9,
        "status": "orange",
        "keyIndicator": "Poverty headcount (<$2.15/day)",
        "value": 36.1,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2021"
      },
      2: {
        "score": 83.0,
        "status": "green",
        "keyIndicator": "Undernourishment rate",
        "value": 12.3,
        "unit": "%",
        "trend": "stable",
        "source": "FAO / World Bank 2023"
      },
      3: {
        "score": 72.6,
        "status": "green",
        "keyIndicator": "Under-5 mortality rate",
        "value": 73.0,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      4: {
        "score": 26.3,
        "status": "red",
        "keyIndicator": "Primary completion rate",
        "value": 48.43,
        "unit": "%",
        "trend": "stable",
        "source": "UNESCO / World Bank 2023"
      },
      7: {
        "score": 54.5,
        "status": "orange",
        "keyIndicator": "Access to electricity",
        "value": 54.5,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 57.9,
        "status": "yellow",
        "keyIndicator": "GDP per capita growth",
        "value": 1.95,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "GNB",
    "name": "Guinea-Bissau",
    "flag": "🇬🇼",
    "region": "West Africa",
    "population": 2.2,
    "incomeGroup": "Low",
    "sdgScore": 57.9,
    "sdgRank": 37,
    "goals": {
      1: {
        "score": 50.1,
        "status": "orange",
        "keyIndicator": "Poverty headcount (<$2.15/day)",
        "value": 39.9,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2021"
      },
      2: {
        "score": 65.9,
        "status": "yellow",
        "keyIndicator": "Undernourishment rate",
        "value": 22.1,
        "unit": "%",
        "trend": "stable",
        "source": "FAO / World Bank 2023"
      },
      3: {
        "score": 75.8,
        "status": "green",
        "keyIndicator": "Under-5 mortality rate",
        "value": 67.3,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      7: {
        "score": 40.5,
        "status": "orange",
        "keyIndicator": "Access to electricity",
        "value": 40.5,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 57.2,
        "status": "yellow",
        "keyIndicator": "GDP per capita growth",
        "value": 1.87,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "SDN",
    "name": "Sudan",
    "flag": "🇸🇩",
    "region": "North Africa",
    "population": 50.4,
    "incomeGroup": "Low",
    "sdgScore": 57.6,
    "sdgRank": 38,
    "goals": {
      2: {
        "score": 85.2,
        "status": "green",
        "keyIndicator": "Undernourishment rate",
        "value": 11.0,
        "unit": "%",
        "trend": "stable",
        "source": "FAO / World Bank 2021"
      },
      3: {
        "score": 79.1,
        "status": "green",
        "keyIndicator": "Under-5 mortality rate",
        "value": 61.6,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      7: {
        "score": 66.0,
        "status": "yellow",
        "keyIndicator": "Access to electricity",
        "value": 66.0,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 0,
        "status": "red",
        "keyIndicator": "GDP per capita growth",
        "value": -14.66,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "NGA",
    "name": "Nigeria",
    "flag": "🇳🇬",
    "region": "West Africa",
    "population": 232.7,
    "incomeGroup": "Lower-middle",
    "sdgScore": 56.9,
    "sdgRank": 39,
    "goals": {
      1: {
        "score": 47.8,
        "status": "orange",
        "keyIndicator": "Poverty headcount (<$2.15/day)",
        "value": 41.8,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2022"
      },
      2: {
        "score": 69.7,
        "status": "yellow",
        "keyIndicator": "Undernourishment rate",
        "value": 19.9,
        "unit": "%",
        "trend": "stable",
        "source": "FAO / World Bank 2023"
      },
      3: {
        "score": 48.2,
        "status": "orange",
        "keyIndicator": "Under-5 mortality rate",
        "value": 115.6,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      7: {
        "score": 61.2,
        "status": "yellow",
        "keyIndicator": "Access to electricity",
        "value": 61.2,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 57.7,
        "status": "yellow",
        "keyIndicator": "GDP per capita growth",
        "value": 1.92,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "AGO",
    "name": "Angola",
    "flag": "🇦🇴",
    "region": "Central Africa",
    "population": 37.9,
    "incomeGroup": "Lower-middle",
    "sdgScore": 56.1,
    "sdgRank": 40,
    "goals": {
      2: {
        "score": 65.2,
        "status": "yellow",
        "keyIndicator": "Undernourishment rate",
        "value": 22.5,
        "unit": "%",
        "trend": "stable",
        "source": "FAO / World Bank 2023"
      },
      3: {
        "score": 86.3,
        "status": "green",
        "keyIndicator": "Under-5 mortality rate",
        "value": 49.0,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      4: {
        "score": 25.5,
        "status": "red",
        "keyIndicator": "Primary completion rate",
        "value": 47.86,
        "unit": "%",
        "trend": "stable",
        "source": "UNESCO / World Bank 2023"
      },
      7: {
        "score": 51.1,
        "status": "orange",
        "keyIndicator": "Access to electricity",
        "value": 51.1,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 52.4,
        "status": "orange",
        "keyIndicator": "GDP per capita growth",
        "value": 1.29,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "BFA",
    "name": "Burkina Faso",
    "flag": "🇧🇫",
    "region": "West Africa",
    "population": 23.5,
    "incomeGroup": "Low",
    "sdgScore": 52.6,
    "sdgRank": 41,
    "goals": {
      1: {
        "score": 47.4,
        "status": "orange",
        "keyIndicator": "Poverty headcount (<$2.15/day)",
        "value": 42.1,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2021"
      },
      2: {
        "score": 81.6,
        "status": "green",
        "keyIndicator": "Undernourishment rate",
        "value": 13.1,
        "unit": "%",
        "trend": "stable",
        "source": "FAO / World Bank 2023"
      },
      3: {
        "score": 71.5,
        "status": "green",
        "keyIndicator": "Under-5 mortality rate",
        "value": 74.9,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      4: {
        "score": 31.4,
        "status": "red",
        "keyIndicator": "Primary completion rate",
        "value": 51.99,
        "unit": "%",
        "trend": "stable",
        "source": "UNESCO / World Bank 2024"
      },
      7: {
        "score": 21.7,
        "status": "red",
        "keyIndicator": "Access to electricity",
        "value": 21.7,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 62.3,
        "status": "yellow",
        "keyIndicator": "GDP per capita growth",
        "value": 2.47,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "MWI",
    "name": "Malawi",
    "flag": "🇲🇼",
    "region": "East Africa",
    "population": 21.7,
    "incomeGroup": "Low",
    "sdgScore": 52.1,
    "sdgRank": 42,
    "goals": {
      2: {
        "score": 67.1,
        "status": "yellow",
        "keyIndicator": "Undernourishment rate",
        "value": 21.4,
        "unit": "%",
        "trend": "stable",
        "source": "FAO / World Bank 2023"
      },
      3: {
        "score": 86.4,
        "status": "green",
        "keyIndicator": "Under-5 mortality rate",
        "value": 48.8,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      4: {
        "score": 57.3,
        "status": "yellow",
        "keyIndicator": "Primary completion rate",
        "value": 70.14,
        "unit": "%",
        "trend": "stable",
        "source": "UNESCO / World Bank 2024"
      },
      7: {
        "score": 15.6,
        "status": "red",
        "keyIndicator": "Access to electricity",
        "value": 15.6,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 34.1,
        "status": "red",
        "keyIndicator": "GDP per capita growth",
        "value": -0.91,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "NER",
    "name": "Niger",
    "flag": "🇳🇪",
    "region": "West Africa",
    "population": 27.0,
    "incomeGroup": "Low",
    "sdgScore": 48.4,
    "sdgRank": 43,
    "goals": {
      1: {
        "score": 24.4,
        "status": "red",
        "keyIndicator": "Poverty headcount (<$2.15/day)",
        "value": 60.5,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2021"
      },
      2: {
        "score": 81.9,
        "status": "green",
        "keyIndicator": "Undernourishment rate",
        "value": 12.9,
        "unit": "%",
        "trend": "stable",
        "source": "FAO / World Bank 2023"
      },
      3: {
        "score": 51.0,
        "status": "orange",
        "keyIndicator": "Under-5 mortality rate",
        "value": 110.7,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      4: {
        "score": 15.4,
        "status": "red",
        "keyIndicator": "Primary completion rate",
        "value": 40.76,
        "unit": "%",
        "trend": "stable",
        "source": "UNESCO / World Bank 2024"
      },
      7: {
        "score": 20.1,
        "status": "red",
        "keyIndicator": "Access to electricity",
        "value": 20.1,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 97.8,
        "status": "green",
        "keyIndicator": "GDP per capita growth",
        "value": 6.74,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "ZMB",
    "name": "Zambia",
    "flag": "🇿🇲",
    "region": "Southern Africa",
    "population": 21.3,
    "incomeGroup": "Lower-middle",
    "sdgScore": 47.5,
    "sdgRank": 44,
    "goals": {
      1: {
        "score": 10.4,
        "status": "red",
        "keyIndicator": "Poverty headcount (<$2.15/day)",
        "value": 71.7,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2022"
      },
      2: {
        "score": 39.7,
        "status": "red",
        "keyIndicator": "Undernourishment rate",
        "value": 37.2,
        "unit": "%",
        "trend": "stable",
        "source": "FAO / World Bank 2023"
      },
      3: {
        "score": 86.6,
        "status": "green",
        "keyIndicator": "Under-5 mortality rate",
        "value": 48.4,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      7: {
        "score": 51.1,
        "status": "orange",
        "keyIndicator": "Access to electricity",
        "value": 51.1,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 49.5,
        "status": "orange",
        "keyIndicator": "GDP per capita growth",
        "value": 0.94,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "LBR",
    "name": "Liberia",
    "flag": "🇱🇷",
    "region": "West Africa",
    "population": 5.6,
    "incomeGroup": "Low",
    "sdgScore": 47.3,
    "sdgRank": 45,
    "goals": {
      2: {
        "score": 42.6,
        "status": "orange",
        "keyIndicator": "Undernourishment rate",
        "value": 35.5,
        "unit": "%",
        "trend": "stable",
        "source": "FAO / World Bank 2023"
      },
      3: {
        "score": 64.9,
        "status": "yellow",
        "keyIndicator": "Under-5 mortality rate",
        "value": 86.4,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      4: {
        "score": 39.8,
        "status": "red",
        "keyIndicator": "Primary completion rate",
        "value": 57.85,
        "unit": "%",
        "trend": "stable",
        "source": "UNESCO / World Bank 2022"
      },
      7: {
        "score": 32.5,
        "status": "red",
        "keyIndicator": "Access to electricity",
        "value": 32.5,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 56.7,
        "status": "yellow",
        "keyIndicator": "GDP per capita growth",
        "value": 1.8,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "MOZ",
    "name": "Mozambique",
    "flag": "🇲🇿",
    "region": "Southern Africa",
    "population": 34.6,
    "incomeGroup": "Low",
    "sdgScore": 46.4,
    "sdgRank": 46,
    "goals": {
      1: {
        "score": 0,
        "status": "red",
        "keyIndicator": "Poverty headcount (<$2.15/day)",
        "value": 81.4,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2022"
      },
      2: {
        "score": 66.4,
        "status": "yellow",
        "keyIndicator": "Undernourishment rate",
        "value": 21.8,
        "unit": "%",
        "trend": "stable",
        "source": "FAO / World Bank 2023"
      },
      3: {
        "score": 80.3,
        "status": "green",
        "keyIndicator": "Under-5 mortality rate",
        "value": 59.4,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      4: {
        "score": 60.5,
        "status": "yellow",
        "keyIndicator": "Primary completion rate",
        "value": 72.37,
        "unit": "%",
        "trend": "stable",
        "source": "UNESCO / World Bank 2022"
      },
      7: {
        "score": 36.0,
        "status": "red",
        "keyIndicator": "Access to electricity",
        "value": 36.0,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 35.1,
        "status": "red",
        "keyIndicator": "GDP per capita growth",
        "value": -0.79,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "MDG",
    "name": "Madagascar",
    "flag": "🇲🇬",
    "region": "East Africa",
    "population": 32.0,
    "incomeGroup": "Low",
    "sdgScore": 44.5,
    "sdgRank": 47,
    "goals": {
      1: {
        "score": 13.5,
        "status": "red",
        "keyIndicator": "Poverty headcount (<$2.15/day)",
        "value": 69.2,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2021"
      },
      2: {
        "score": 35.7,
        "status": "red",
        "keyIndicator": "Undernourishment rate",
        "value": 39.5,
        "unit": "%",
        "trend": "stable",
        "source": "FAO / World Bank 2023"
      },
      3: {
        "score": 78.6,
        "status": "green",
        "keyIndicator": "Under-5 mortality rate",
        "value": 62.4,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      4: {
        "score": 43.9,
        "status": "orange",
        "keyIndicator": "Primary completion rate",
        "value": 60.71,
        "unit": "%",
        "trend": "stable",
        "source": "UNESCO / World Bank 2024"
      },
      7: {
        "score": 39.4,
        "status": "red",
        "keyIndicator": "Access to electricity",
        "value": 39.4,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 55.8,
        "status": "yellow",
        "keyIndicator": "GDP per capita growth",
        "value": 1.69,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "SSD",
    "name": "South Sudan",
    "flag": "🇸🇸",
    "region": "East Africa",
    "population": 11.9,
    "incomeGroup": "Unknown",
    "sdgScore": 43.3,
    "sdgRank": 48,
    "goals": {
      2: {
        "score": 65.6,
        "status": "yellow",
        "keyIndicator": "Undernourishment rate",
        "value": 22.3,
        "unit": "%",
        "trend": "stable",
        "source": "FAO / World Bank 2023"
      },
      3: {
        "score": 59.0,
        "status": "yellow",
        "keyIndicator": "Under-5 mortality rate",
        "value": 96.7,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      7: {
        "score": 5.4,
        "status": "red",
        "keyIndicator": "Access to electricity",
        "value": 5.4,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      }
    }
  },
  {
    "iso": "COD",
    "name": "DR Congo",
    "flag": "🇨🇩",
    "region": "Central Africa",
    "population": 109.3,
    "incomeGroup": "Low",
    "sdgScore": 42.0,
    "sdgRank": 49,
    "goals": {
      1: {
        "score": 0,
        "status": "red",
        "keyIndicator": "Poverty headcount (<$2.15/day)",
        "value": 85.3,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2020"
      },
      2: {
        "score": 37.4,
        "status": "red",
        "keyIndicator": "Undernourishment rate",
        "value": 38.5,
        "unit": "%",
        "trend": "stable",
        "source": "FAO / World Bank 2023"
      },
      3: {
        "score": 63.0,
        "status": "yellow",
        "keyIndicator": "Under-5 mortality rate",
        "value": 89.7,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      4: {
        "score": 65.3,
        "status": "yellow",
        "keyIndicator": "Primary completion rate",
        "value": 75.71,
        "unit": "%",
        "trend": "stable",
        "source": "UNESCO / World Bank 2023"
      },
      7: {
        "score": 22.1,
        "status": "red",
        "keyIndicator": "Access to electricity",
        "value": 22.1,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 64.5,
        "status": "yellow",
        "keyIndicator": "GDP per capita growth",
        "value": 2.74,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "SOM",
    "name": "Somalia",
    "flag": "🇸🇴",
    "region": "East Africa",
    "population": 19.0,
    "incomeGroup": "Low",
    "sdgScore": 41.2,
    "sdgRank": 50,
    "goals": {
      2: {
        "score": 11.8,
        "status": "red",
        "keyIndicator": "Undernourishment rate",
        "value": 53.2,
        "unit": "%",
        "trend": "stable",
        "source": "FAO / World Bank 2023"
      },
      3: {
        "score": 56.5,
        "status": "yellow",
        "keyIndicator": "Under-5 mortality rate",
        "value": 101.1,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      7: {
        "score": 50.3,
        "status": "orange",
        "keyIndicator": "Access to electricity",
        "value": 50.3,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 46.2,
        "status": "orange",
        "keyIndicator": "GDP per capita growth",
        "value": 0.55,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "BDI",
    "name": "Burundi",
    "flag": "🇧🇮",
    "region": "East Africa",
    "population": 14.0,
    "incomeGroup": "Low",
    "sdgScore": 40.0,
    "sdgRank": 51,
    "goals": {
      1: {
        "score": 7.2,
        "status": "red",
        "keyIndicator": "Poverty headcount (<$2.15/day)",
        "value": 74.2,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2020"
      },
      3: {
        "score": 87.4,
        "status": "green",
        "keyIndicator": "Under-5 mortality rate",
        "value": 47.1,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      7: {
        "score": 11.6,
        "status": "red",
        "keyIndicator": "Access to electricity",
        "value": 11.6,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 53.8,
        "status": "orange",
        "keyIndicator": "GDP per capita growth",
        "value": 1.46,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "TCD",
    "name": "Chad",
    "flag": "🇹🇩",
    "region": "Central Africa",
    "population": 20.3,
    "incomeGroup": "Low",
    "sdgScore": 36.9,
    "sdgRank": 52,
    "goals": {
      1: {
        "score": 50.6,
        "status": "orange",
        "keyIndicator": "Poverty headcount (<$2.15/day)",
        "value": 39.5,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2022"
      },
      2: {
        "score": 48.7,
        "status": "orange",
        "keyIndicator": "Undernourishment rate",
        "value": 32.0,
        "unit": "%",
        "trend": "stable",
        "source": "FAO / World Bank 2023"
      },
      3: {
        "score": 58.7,
        "status": "yellow",
        "keyIndicator": "Under-5 mortality rate",
        "value": 97.3,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      4: {
        "score": 16.9,
        "status": "red",
        "keyIndicator": "Primary completion rate",
        "value": 41.85,
        "unit": "%",
        "trend": "stable",
        "source": "UNESCO / World Bank 2021"
      },
      7: {
        "score": 12.0,
        "status": "red",
        "keyIndicator": "Access to electricity",
        "value": 12.0,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 34.8,
        "status": "red",
        "keyIndicator": "GDP per capita growth",
        "value": -0.83,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  },
  {
    "iso": "CAF",
    "name": "Central African Republic",
    "flag": "🇨🇫",
    "region": "Central Africa",
    "population": 5.3,
    "incomeGroup": "Low",
    "sdgScore": 33.9,
    "sdgRank": 53,
    "goals": {
      1: {
        "score": 10.5,
        "status": "red",
        "keyIndicator": "Poverty headcount (<$2.15/day)",
        "value": 71.6,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2021"
      },
      2: {
        "score": 52.5,
        "status": "orange",
        "keyIndicator": "Undernourishment rate",
        "value": 29.8,
        "unit": "%",
        "trend": "stable",
        "source": "FAO / World Bank 2023"
      },
      3: {
        "score": 63.0,
        "status": "yellow",
        "keyIndicator": "Under-5 mortality rate",
        "value": 89.7,
        "unit": "/1000",
        "trend": "stable",
        "source": "WHO / World Bank 2024"
      },
      7: {
        "score": 17.6,
        "status": "red",
        "keyIndicator": "Access to electricity",
        "value": 17.6,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2023"
      },
      8: {
        "score": 25.9,
        "status": "red",
        "keyIndicator": "GDP per capita growth",
        "value": -1.89,
        "unit": "%",
        "trend": "stable",
        "source": "World Bank 2024"
      }
    }
  }
]

export function getStatusColor(status) {
  const map = { green: '#22c55e', yellow: '#eab308', orange: '#f97316', red: '#ef4444', grey: '#4b5563' }
  return map[status] || map.grey
}

export function getStatusLabel(status) {
  const map = { green: 'On Track', yellow: 'Moderate', orange: 'At Risk', red: 'Off Track', grey: 'No Data' }
  return map[status] || 'Unknown'
}

export function getTrendIcon(trend) {
  return trend === 'improving' ? '↑' : trend === 'worsening' ? '↓' : '→'
}

export function getOverallStatus(score) {
  if (score >= 70) return 'green'
  if (score >= 55) return 'yellow'
  if (score >= 40) return 'orange'
  return 'red'
}

export function computeRegionSummary() {
  const regionMap = {}
  countries.forEach(c => {
    if (!regionMap[c.region]) regionMap[c.region] = { count: 0, totalScore: 0 }
    regionMap[c.region].count++
    regionMap[c.region].totalScore += c.sdgScore
  })
  return Object.entries(regionMap).map(([region, d]) => ({
    region,
    avgScore: +(d.totalScore / d.count).toFixed(1),
    count: d.count,
  })).sort((a, b) => b.avgScore - a.avgScore)
}

export const SECTOR_STATS = {
  totalCountries: 54,
  coveredCountries: countries.length,
  dataYear: '2020–2023',
  lastUpdated: 'April 2026',
  goalsTracked: SDG_GOALS.length,
  onTrackCount: countries.filter(c => c.sdgScore >= 70).length,
  atRiskCount: countries.filter(c => c.sdgScore < 50).length,
  topCountry: [...countries].sort((a, b) => b.sdgScore - a.sdgScore)[0],
  bottomCountry: [...countries].sort((a, b) => a.sdgScore - b.sdgScore)[0],
}
